# relativeURLs = true
# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
BaseURL = "https://nonotnones.github.io/secu/"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "workshop"
  # Git hub repo link
  editURL = ""
  description = ""
  author = "tuanatran.vn@gmail.com"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = true
  
[Languages]
[Languages.en]
title = "Essentials in Cybersecurity"
weight = 1
languageName = "English"




